---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bergejkg/public_html/
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH